[package]
name                   = "kobe-evm"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
readme                 = "README.md"
description            = "Ethereum HD wallet derivation for Kobe"
keywords               = ["ethereum", "wallet", "crypto", "no_std"]
categories             = ["cryptography", "no-std"]

[features]
default = ["std"]
std     = ["kobe-core/std"]

[dependencies]
kobe-core                  = { workspace = true, features = ["bip32"] }
alloy-primitives.workspace = true

[lints]
workspace = true
