[package]
name                   = "kobe-xrpl"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
readme                 = "README.md"
description            = "XRP Ledger wallet for Kobe"
keywords               = ["xrpl", "ripple", "wallet", "crypto", "no_std"]
categories             = ["cryptography", "no-std"]

[features]
default = ["std"]
std     = ["kobe-core/std"]

[dependencies]
kobe-core      = { workspace = true, features = ["bip32", "encoding"] }
bs58.workspace = true

[lints]
workspace = true
