[package]
name                   = "kobe-spark"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
readme                 = "README.md"
description            = "Spark (Bitcoin L2) wallet for Kobe"
keywords               = ["spark", "bitcoin", "wallet", "crypto"]
categories             = ["cryptography", "no-std"]

[features]
default = ["std"]
std     = ["kobe-core/std"]

[dependencies]
kobe-core        = { workspace = true, features = ["bip32"] }
bech32.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
