[package]
name                   = "kobe-cosmos"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
authors.workspace      = true
readme                 = "README.md"
description            = "Cosmos wallet for Kobe"
keywords               = ["cosmos", "wallet", "crypto", "no_std"]
categories             = ["cryptography", "no-std"]

[features]
default = ["std"]
std     = ["kobe-core/std"]

[dependencies]
kobe-core        = { workspace = true, features = ["bip32", "encoding"] }
bech32.workspace = true

[lints]
workspace = true
